import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/donation_model.dart';

class DonationService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Collection reference
  CollectionReference get _donationsCollection =>
      _firestore.collection('donations');

  // Upload donation image to Storage
  Future<String> uploadDonationImage(File file) async {
    final user = _auth.currentUser;
    if (user == null) throw Exception("User not logged in");

    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final filename = 'donation_${user.uid}_$timestamp.jpg';
    final ref = _storage.ref().child('donations/$filename');

    final uploadTask = await ref.putFile(file);
    return await uploadTask.ref.getDownloadURL();
  }

  // Create new donation
  Future<void> createDonation({
    required String medicineName,
    required String imageUrl,
    required int quantity,
    required DateTime expiryDate,
    required String phone,
    required String location,
    required String donorName,
    required String userType,
  }) async {
    final user = _auth.currentUser;
    if (user == null) throw Exception("User not logged in");

    final donation = Donation(
      id: '', // Generated by Firestore
      medicineName: medicineName,
      imageUrl: imageUrl,
      quantity: quantity,
      expiryDate: expiryDate,
      phone: phone,
      userId: user.uid,
      userType: userType,
      createdAt: DateTime.now(),
      location: location,
      donorName: donorName,
    );

    await _donationsCollection.add(donation.toMap());
  }

  // Get active donations stream (not expired)
  Stream<List<Donation>> getActiveDonations() {
    final now = DateTime.now();
    return _donationsCollection
        .where('expiryDate', isGreaterThan: Timestamp.fromDate(now))
        .orderBy('expiryDate')
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) =>
              Donation.fromMap(doc.data() as Map<String, dynamic>, doc.id))
          .toList();
    });
  }

  // Toggle recommendation (Doctor only)
  Future<void> toggleRecommendation(String donationId, bool isRecommended) async {
    await _donationsCollection.doc(donationId).update({
      'isRecommended': isRecommended,
    });
  }

  // Delete donation
  Future<void> deleteDonation(String donationId) async {
    await _donationsCollection.doc(donationId).delete();
  }
  
  // Verify Doctor (Helper)
  Future<void> verifyDoctor(String doctorUserId, bool isVerified) async {
    await _firestore.collection('users').doc(doctorUserId).update({
      'isVerified': isVerified,
    });
  }

  // Check if current user is a verified doctor
  Future<bool> isCurrentDoctorVerified() async {
    final user = _auth.currentUser;
    if (user == null) return false;
    
    final doc = await _firestore.collection('users').doc(user.uid).get();
    if (doc.exists) {
      return doc.data()?['isVerified'] == true && doc.data()?['role'] == 'doctor';
    }
    return false;
  }
}
