import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/medical_record.dart';

class MedicalRecordsService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;

  Future<void> uploadMedicalRecord({
    required String patientId,
    required String name,
    required String type,
    File? file,
    Uint8List? bytes,
  }) async {
    // 1. Upload file to Firebase Storage
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final filename = 'record_$timestamp.$type';
    final ref = _storage.ref().child('medical_records/$patientId/$filename');
    
    final TaskSnapshot uploadTask;
    if (kIsWeb) {
      if (bytes == null) throw Exception("Bytes are required for web upload");
      uploadTask = await ref.putData(bytes, SettableMetadata(contentType: 'application/octet-stream'));
    } else {
      if (file == null) throw Exception("File is required for mobile upload");
      uploadTask = await ref.putFile(file);
    }
    final url = await uploadTask.ref.getDownloadURL();

    // 2. Save metadata to Firestore (using the exact same structure expected by doctor_app)
    final record = MedicalRecord(
      id: '', // Will be generated by Firestore
      name: name,
      url: url,
      type: type,
      date: DateTime.now(),
    );

    await _firestore
        .collection('users')
        .doc(patientId)
        .collection('medical_records')
        .add(record.toMap());
  }
}
